### ISSUE TITLE
排版建议

### ISSUE THREAD

**Issue by 0x01f7** [JuanitoFatas/Computer-Science-Glossary#13]
1. 依据单词的字典序升序排列
    + 新增词汇避免重复添加
    + 翻译词汇避免类似词汇译法差别过大，比如 debug，debuging
2. 移除或合并同义词，比如 REPL，当前存在三个条目，且译法不一致；又如 Turning machine(s)
3. 正确使用大小写与 - 号，比如 Amortized analysis 似乎没有必要首字母大写？

**Comment by JuanitoFatas** [comment]
@0x01f7 Added you as collaborator, feel free to make any changes!
